// ********RoostGPT********
// Test generated by RoostGPT for test checkNodejsDepsInstalled using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
const request = require('supertest');
const express = require('express');
const bodyParser = require('body-parser');
const todoRoutes = express.Router();

let Todo = require('./todo.model');

const app = express();
app.use(bodyParser.json());
app.use('/', todoRoutes);

todoRoutes.route('/:id').get(function (req, res) {
  let id = req.params.id;
  Todo.findById(id, function (err, todo) {
    res.json(todo);
  });
})

describe('GET /:id', () => {
  test('responds with json', async () => {
    const todo = new Todo({ title: 'Test todo', description: 'Test todo description' });
    await todo.save();

    const response = await request(app).get(`/${todo.id}`);
    expect(response.status).toBe(200);
    expect(response.body.title).toEqual(todo.title);
    expect(response.body.description).toEqual(todo.description);
  });

  test('responds with 404 for non-existing todo', async () => {
    const response = await request(app).get('/nonexistingid');
    expect(response.status).toBe(404);
  });
});
