// ********RoostGPT********
// Test generated by RoostGPT for test checkNodejsDepsInstalled using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
const request = require('supertest');
const app = require('./server');

// Test suite
describe('Test the root path', function() {

  // Test case: Should respond with a success message when server is running
  test('Should respond with a success message when server is running', async function() {
    const response = await request(app).get('/');
    expect(response.statusCode).toBe(200);
    expect(response.text).toBe('Server is running on port: 4000');
  });

  // Test case: Should respond with an error message when server is not running
  test('Should respond with an error message when server is not running', async function() {
    const response = await request(app).get('/');
    expect(response.statusCode).toBe(500);
    expect(response.text).toBe('Server is not running');
  });
});
