// ********RoostGPT********
// Test generated by RoostGPT for test checkNodejsDepsInstalled using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
const mongoose = require('mongoose');
const db = mongoose.connection;

describe('DB Connection', () => {
  beforeAll(() => {
    mongoose.connect('mongodb://localhost/test', { useNewUrlParser: true, useUnifiedTopology: true });
  });

  test('DB Connection Success', done => {
    db.once('open', () => {
      expect(db.readyState).toBe(1);
      done();
    });
  });

  test('DB Connection Fail', done => {
    const badConnection = mongoose.createConnection('mongodb://localhost:1/test', { useNewUrlParser: true, useUnifiedTopology: true });

    badConnection.on('error', err => {
      expect(err).toBeTruthy();
      done();
    });
  });

  afterAll((done) => {
    mongoose.disconnect(done);
  });
});
