// ********RoostGPT********
// Test generated by RoostGPT for test checkNodejsDepsInstalled using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
const request = require('supertest');
const app = require('./server');
jest.mock('./todo.model');

describe('POST /add', () => {
  beforeEach(() => {
    Todo.mockClear();
  });

  test('should respond with 200 status and success message when todo is successfully added', async () => {
    Todo.mockImplementation(() => {
      return {
        save: () => {
          return Promise.resolve();
        }
      };
    });

    const response = await request(app)
      .post('/add')
      .send({text: 'Test todo'});

    expect(response.status).toBe(200);
    expect(response.body.todo).toBe('todo added successfully');
  });

  test('should respond with 400 status and failure message when adding todo fails', async () => {
    Todo.mockImplementation(() => {
      return {
        save: () => {
          return Promise.reject();
        }
      };
    });

    const response = await request(app)
      .post('/add')
      .send({text: 'Test todo'});

    expect(response.status).toBe(400);
    expect(response.text).toBe('adding new todo failed');
  });
});
